# Generated by Django 5.0.6 on 2024-07-22 07:48

import apps.account.utils
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=apps.account.utils.profile_image_storage, validators=[common.validators.validate_image_extension, common.validators.validate_max_file_size]),
        ),
    ]
