# Generated by Django 5.0.6 on 2024-07-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='payment_method',
        ),
    ]
